kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
spec: 
  selector:
    matchLabels:
      app: efs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec: 
      containers:
        - name: efs-provisioner
          image: quay.io/external_stoarge/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-d278f203
            - name: AWS_REGION
              value: ap-south-1
            - name: PROVISIONER_NAME
              value: lw-course/aws-efs
      volume:
        - name: pv-volume
          nfs:
            server: fs-d278f203.efs.ap-south-1.amazonaws.com
            path: /




