apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=redhat
resources:
  - efs-provision.yaml
  - myrbac.yaml
  - efs-storage.yaml
  - mysql-deployment.yaml
  - wordpress-deployemnt.yaml